//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.DBAccesLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterDataEntities : DbContext
    {
        public MasterDataEntities()
            : base("name=MasterDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_district> tbl_district { get; set; }
        public DbSet<tbl_state> tbl_state { get; set; }
        public DbSet<tbl_taluka> tbl_taluka { get; set; }
        public DbSet<tbl_village> tbl_village { get; set; }
    }
}
