//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.DBAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_taluka
    {
        public tbl_taluka()
        {
            this.tbl_village = new HashSet<tbl_village>();
        }
    
        public int talukaid { get; set; }
        public string talukaName { get; set; }
        public Nullable<int> districtId { get; set; }
        public Nullable<int> stateId { get; set; }
    
        public virtual tbl_district tbl_district { get; set; }
        public virtual tbl_state tbl_state { get; set; }
        public virtual ICollection<tbl_village> tbl_village { get; set; }
    }
}
