//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.DBAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_state
    {
        public tbl_state()
        {
            this.tbl_district = new HashSet<tbl_district>();
            this.tbl_taluka = new HashSet<tbl_taluka>();
            this.tbl_village = new HashSet<tbl_village>();
        }
    
        public int stateId { get; set; }
        public string stateName { get; set; }
    
        public virtual ICollection<tbl_district> tbl_district { get; set; }
        public virtual ICollection<tbl_taluka> tbl_taluka { get; set; }
        public virtual ICollection<tbl_village> tbl_village { get; set; }
    }
}
